### ISSUE TITLE
Changing/Modifying HINT message below the password 

### ISSUE THREAD

**Issue by todarom** [DanielSantoro/wc-password-strength-settings#5]
when customer creates an account the HINT message below the password still tells the customer to use a 12 character password even though a weaker password will be accepted.  How do you modify or delete this HINT message in WC?

**Comment by rshaw01** [comment]
Hi. We noticed the same issue. Even though weak is selected, WooCommerce still shows the 'strong' message. We would like to show the appropriate message. If this is in the roadmap as an enhancement, could you give us an idea of when it will be released. We are happy to use the plugin if the feature is on its way. Cheers. Roger
